const dummyEvents = [
  {
    id: '1',
    userA: 'Alice',
    userB: 'Bob',
    partnerNationality: 'Japan',
    latitude: 25.0330,
    longitude: 121.5654,
    locationCountry: 'Taiwan',
    musicLink: 'https://youtu.be/dQw4w9WgXcQ',
    description: '今天在台北101前遇到Bob，他說這首歌讓他想起家鄉的夏日祭典。我們聊到深夜，發現音樂真的能跨越語言障礙，那種共鳴的感覺太神奇了！',
    createdAt: '2025-05-20',
  },
  {
    id: '2',
    userA: 'Charlie',
    userB: 'Diana',
    partnerNationality: 'USA',
    latitude: 35.6895,
    longitude: 139.6917,
    locationCountry: 'Japan',
    musicLink: 'https://open.spotify.com/track/abcdefg',
    description: '在澀谷人潮中偶遇Diana，她推薦的獨立音樂完全顛覆了我對美式音樂的刻板印象。我們在星巴克坐了三小時，她說這首歌陪她度過了大學最低潮的時期。',
    createdAt: '2025-05-25',
  },
  {
    id: '3',
    userA: 'Wei',
    userB: 'Sophie',
    partnerNationality: 'France',
    latitude: 48.8584,
    longitude: 2.2945,
    locationCountry: 'France',
    musicLink: 'https://www.youtube.com/watch?v=3JZ4pnNtyxQ',
    description: '鐵塔夜景下，Sophie用她略帶沙啞的聲音哼著這首香頌，我瞬間被感動到起雞皮疙瘩。她說這是她奶奶最愛的歌，每次聽都會想哭。巴黎的浪漫不只是風景，更是這些真實的情感連結。',
    createdAt: '2025-06-01',
  },
  {
    id: '4',
    userA: 'Kenji',
    userB: 'Mina',
    partnerNationality: 'Korea',
    latitude: 37.5665,
    longitude: 126.9780,
    locationCountry: 'Korea',
    musicLink: 'https://open.spotify.com/track/xyz123',
    description: 'Mina超級熱情！她一聽到我來自日本就開始狂推K-pop，說這首歌的MV她看了至少50遍。我們在市廳附近的咖啡廳討論了兩國音樂的差異，她的熱忱讓我重新認識了韓流文化。',
    createdAt: '2025-06-03',
  },
  {
    id: '5',
    userA: 'Emily',
    userB: 'Lucas',
    partnerNationality: 'Germany',
    latitude: 52.5200,
    longitude: 13.4050,
    locationCountry: 'Germany',
    musicLink: 'https://youtu.be/ZZ5LpwO-An4',
    description: '在圍牆遺址旁聽著德國電子樂，Lucas告訴我這種音樂如何陪伴柏林人走過分裂與重建。那種厚重的歷史感配上節拍，讓我對這座城市有了全新的理解。音樂真的承載了太多故事。',
    createdAt: '2025-06-05',
  },
  {
    id: '6',
    userA: 'Yuki',
    userB: 'Anna',
    partnerNationality: 'Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    locationCountry: 'Canada',
    musicLink: 'https://open.spotify.com/track/trackid1',
    description: '湖邊的夕陽配上Anna推薦的日系搖滾，整個氛圍絕了！她說第一次聽日本音樂是因為動漫，現在已經深深愛上這種細膩的情感表達。我們約好下次要一起去日本的livehouse。',
    createdAt: '2025-06-07',
  },
  {
    id: '7',
    userA: 'Oscar',
    userB: 'Liam',
    partnerNationality: 'USA',
    latitude: 40.7128,
    longitude: -74.0060,
    locationCountry: 'USA',
    musicLink: 'https://www.youtube.com/watch?v=ktvTqknDobU',
    description: '中央公園的午後，Liam跟我分享了他最愛的嘻哈歌手。他說這首歌陪他度過了在布朗克斯長大的艱難歲月，每個節拍都是他的人生寫照。那種真實的力量讓我對嘻哈文化有了更深的敬意。',
    createdAt: '2025-06-10',
  },
  {
    id: '8',
    userA: 'Mei',
    userB: 'Pierre',
    partnerNationality: 'France',
    latitude: 22.6273,
    longitude: 120.3014,
    locationCountry: 'Taiwan',
    musicLink: 'https://open.spotify.com/track/trackid2',
    description: '在駁二遇到Pierre真是意外驚喜！他的中文超流利，還跟我解釋法國饒舌的社會意義。我們邊喝珍奶邊聊音樂，他說台灣的創意能量讓他想留下來創作。文化交流就是這麼美好！',
    createdAt: '2025-06-12',
  },
  {
    id: '9',
    userA: 'Ivan',
    userB: 'Sasha',
    partnerNationality: 'Germany',
    latitude: 50.1109,
    longitude: 8.6821,
    locationCountry: 'Germany',
    musicLink: 'https://youtu.be/9bZkp7q19f0',
    description: '法蘭克福的老城區，Sasha竟然推薦韓國流行歌給我！她說德國的K-pop粉絲社群超活躍，還帶我去了當地的韓流商店。看到歐洲人對亞洲文化的熱愛，真的很感動。',
    createdAt: '2025-06-15',
  },
  {
    id: '10',
    userA: 'Tina',
    userB: 'Jasper',
    partnerNationality: 'Taiwan',
    latitude: 24.1477,
    longitude: 120.6736,
    locationCountry: 'Taiwan',
    musicLink: 'https://open.spotify.com/track/trackid3',
    description: '歌劇院外偶遇的Jasper讓我重新愛上台語歌！他說這些老歌承載著台灣人的集體記憶，每個字都有故事。我們一起哼著歌走過台中街頭，那種歸屬感好久沒有過了。',
    createdAt: '2025-06-18',
  },
  {
    id: '11',
    userA: 'Sophia',
    userB: 'David',
    partnerNationality: 'USA',
    latitude: 34.0522,
    longitude: -118.2437,
    locationCountry: 'USA',
    musicLink: 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y',
    description: '洛杉磯的陽光下，David彈著吉他唱這首經典搖滾，路人都停下來聽。他說音樂是他逃離現實壓力的唯一方式，那種純粹的熱愛讓我想起自己為什麼開始愛音樂。',
    createdAt: '2025-06-20',
  },
  {
    id: '12',
    userA: 'Hiro',
    userB: 'Maggie',
    partnerNationality: 'Canada',
    latitude: 45.5017,
    longitude: -73.5673,
    locationCountry: 'Canada',
    musicLink: 'https://open.spotify.com/track/trackid4',
    description: '蒙特婁港口的爵士樂聲中遇見Maggie，她的法語腔調配上爵士樂意外地迷人。她說這首歌讓她想起和已故爺爺的回憶，我們都哭了。有時候音樂就是這樣，觸碰到心裡最柔軟的地方。',
    createdAt: '2025-06-22',
  },
  {
    id: '13',
    userA: 'Lina',
    userB: 'Tom',
    partnerNationality: 'Japan',
    latitude: 35.0116,
    longitude: 135.7681,
    locationCountry: 'Japan',
    musicLink: 'https://youtu.be/2Vv-BfVoq4g',
    description: '鴨川邊的櫻花雖然已經凋謝，但Tom推薦的這首抒情歌讓整個氛圍變得好浪漫。他說每次失戀都聽這首歌，現在終於能笑著分享了。京都的美不只在風景，更在這些真摯的情感交流。',
    createdAt: '2025-06-25',
  },
  {
    id: '14',
    userA: 'Ming',
    userB: 'Sarah',
    partnerNationality: 'France',
    latitude: 43.6047,
    longitude: 1.4442,
    locationCountry: 'France',
    musicLink: 'https://open.spotify.com/track/trackid5',
    description: '土魯斯廣場上，Sarah跟我分享她最愛的電子爵士。她說這種fusion風格就像她的人生一樣，混合了各種元素卻意外和諧。我們聊到法國南部的慵懶生活步調，決定要慢下來享受音樂。',
    createdAt: '2025-06-28',
  },
  {
    id: '15',
    userA: 'Ethan',
    userB: 'Jin',
    partnerNationality: 'Korea',
    latitude: 37.5665,
    longitude: 126.9780,
    locationCountry: 'Korea',
    musicLink: 'https://www.youtube.com/watch?v=RgKAFK5djSk',
    description: '清溪川的水聲配上Jin輕柔的歌聲，整個首爾突然變得好安靜。他說韓國民謠是他心靈的避風港，在這個競爭激烈的社會裡特別珍貴。我們約好下次要去弘大的民謠酒吧繼續聊。',
    createdAt: '2025-07-01',
  },
  {
    id: '16',
    userA: 'Ava',
    userB: 'Lucas',
    partnerNationality: 'Germany',
    latitude: 48.1351,
    longitude: 11.5820,
    locationCountry: 'Germany',
    musicLink: 'https://open.spotify.com/track/trackid6',
    description: '慕尼黑啤酒節的熱鬧氛圍中，Lucas堅持要我聽這首傳統民謠。他說即使在全球化的時代，保持文化根源還是很重要。手拿啤酒聽著古老旋律，我突然理解了什麼叫文化傳承。',
    createdAt: '2025-07-03',
  },
  {
    id: '17',
    userA: 'Joy',
    userB: 'Sam',
    partnerNationality: 'USA',
    latitude: 37.7749,
    longitude: -122.4194,
    locationCountry: 'USA',
    musicLink: 'https://youtu.be/OPf0YbXqDm0',
    description: '金門公園的草地上，Sam放著這首流行樂邊做瑜伽，整個畫面太chill了！他說舊金山的自由氛圍讓他找到內心平靜，音樂是他冥想的媒介。我也跟著做了幾個動作，意外地放鬆。',
    createdAt: '2025-07-05',
  },
  {
    id: '18',
    userA: 'Chloe',
    userB: 'Yuta',
    partnerNationality: 'Japan',
    latitude: 35.6895,
    longitude: 139.6917,
    locationCountry: 'Japan',
    musicLink: 'https://open.spotify.com/track/trackid7',
    description: '新宿站的人流中，Yuta戴著耳機跟我分享最新的J-pop。他說這首歌的編曲細節讓他著迷，我們站在那裡反覆聽了好幾遍。東京的節奏很快，但音樂讓時間慢了下來。',
    createdAt: '2025-07-07',
  },
  {
    id: '19',
    userA: 'Jack',
    userB: 'Olivia',
    partnerNationality: 'Canada',
    latitude: 49.2827,
    longitude: -123.1207,
    locationCountry: 'Canada',
    musicLink: 'https://www.youtube.com/watch?v=60ItHLz5WEA',
    description: '溫哥華downtown的夜晚，Olivia帶我去了她最愛的電子音樂club。這首歌在大音響下簡直震撼！她說電子舞曲讓她忘記一切煩惱，純粹享受當下。我們跳到凌晨三點，汗水和音樂融為一體。',
    createdAt: '2025-07-10',
  },
  {
    id: '20',
    userA: 'Yu',
    userB: 'Emma',
    partnerNationality: 'Taiwan',
    latitude: 23.6978,
    longitude: 120.9605,
    locationCountry: 'Taiwan',
    musicLink: 'https://open.spotify.com/track/trackid8',
    description: '阿里山日出的那一刻，Emma輕聲哼著這首台灣民謠，眼眶都紅了。她說這趟旅行讓她重新認識台灣的美，不只是風景，更是人情味。我們在山頂上擁抱，音樂和自然完美融合的瞬間永生難忘。',
    createdAt: '2025-07-12',
  }
];
